### ISSUE TITLE
Ambiguity in CPU Affinity:

### ISSUE THREAD

**Issue by typedef-int-value** [SystemXFiles/process-governor#16]
The description of the scope of CPU Affinity is ambiguous.
If there are 8 cores, it would be better to indicate the range as 0-7.
A typical user might understand it as 1-8.

![image](https://github.com/SystemXFiles/process-governor/assets/14866660/e4b28cf0-7dbe-4906-bf8d-5da2b20edfbe)

**Comment by SystemXFiles** [comment]
@typedef-int-value Hello!
Thank you for bringing this to our attention. There is indeed some ambiguity and I will fix this in the next release.

**Comment by SystemXFiles** [comment]
Fixed in release https://github.com/SystemXFiles/process-governor/releases/tag/v1.2.1
